---
  - name: Create temp header file
    template:
      src: header.j2
      dest: /home/piheta/.header.temp
      owner: piheta
      group: piheta
      mode: '0644'

  - name: Append header to bashrc
    shell:
      cmd: "cat /home/piheta/.header.temp >> /home/piheta/.bashrc"

  - name: Remove temp header file
    file:
      path: /home/piheta/.header.temp
      state: absent

  - name: Install qemu
    community.general.apk:
      name:
        - libvirt-daemon
        - qemu-img
        - qemu-system-x86_64
        - qemu-modules
        - openrc
      state: present

  - name: Create VM disks
    shell:
      cmd: "mkdir -p /opt/vms/disks /opt/vms/isos && [ -f /opt/vms/disks/{{ item.name }}.img ] || qemu-img create -f qcow2 /opt/vms/disks/{{ item.name }}.img {{ item.ssd }}"
    with_items: "{{ nodes }}"

  - name: Download VM Isos
    ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: /opt/vms/isos/{{ item.name }}
      mode: '0644'
    with_items: "{{ isos }}"

  - name: Create VM # cant test yet
    shell:
      cmd: echo done
      #cmd: virt-install --name={{ item.name }} --vcpus={{ item.cpu }} --memory={{ item.ram }} --cdrom=/opt/vms/isos/{{ item.iso }} --disk path=/opt/vms/disks/{{ item.name }}.qcow2 --os-variant={{ item.osvar }}
    with_items: "{{ nodes }}"