---
  - name: Create temp header file
    template:
      src: header.j2
      dest: /home/piheta/.header.temp
      owner: piheta
      group: piheta
      mode: '0644'

  - name: Append header to bashrc
    shell:
      cmd: "cat /home/piheta/.header.temp >> /home/piheta/.bashrc"

  - name: Remove temp header file
    file:
      path: /home/piheta/.header.temp
      state: absent

  - name: Install k3s
    community.general.apk:
      name:
        - k3s
      state: present

  - name: Start service k3s
    service:
      name: k3s
      state: started
      enabled: true
